### ISSUE TITLE
ReferenceError: WebViewer is not defined

### ISSUE THREAD

**Issue by zzj0402** [PDFTron/webviewer-user-bookmarks-nodejs-sample#1]
After running npm i, not much were installed.

**Comment by khein-pdftron** [comment]
Thank you for the bug report. This is fixed by: https://github.com/PDFTron/webviewer-user-bookmarks-nodejs-sample/commit/4f9f143f5a5c7fb81848a04337a073fde9a31b36

npm i and npm start will work properly now.
